# Generated by Django 2.2.2 on 2019-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, verbose_name='Campo SLUG:')),
                ('loja', models.CharField(choices=[('TDC', 'TDC'), ('TES', 'TES'), ('TEU', 'TEU'), ('TMA', 'TMA'), ('TPI', 'TPI'), ('TMO', 'TMO'), ('TEZ', 'TEZ'), ('TED', 'TED'), ('TPP', 'TPP'), ('TIM', 'TIM'), ('TEC', 'TEC'), ('RTT', 'RTT'), ('TSJ', 'TSJ')], max_length=3, verbose_name='Loja:')),
                ('numMinuta', models.CharField(max_length=7, verbose_name='Minuta:')),
                ('numCrp', models.CharField(max_length=5, verbose_name='CRP:')),
                ('tipo', models.CharField(choices=[('T', 'Estético'), ('E', 'Estrutural'), ('R', 'Revisão')], max_length=1, verbose_name='Tipo:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('zona', models.CharField(choices=[('SUL', 'SUL'), ('DIRCEU', 'DIRCEU'), ('NORTE', 'NORTE'), ('LESTE', 'LESTE'), ('TIMON', 'TIMON'), ('R.LESTE', 'R.LESTE'), ('R.NORTE', 'R.NORTE'), ('R.SUL', 'R.SUL'), ('R.DIRCEU', 'R.DIRCEU'), ('R.TIMON', 'R.TIMON')], max_length=8, verbose_name='Zona:')),
                ('dataPrevisaoLimite', models.DateField(verbose_name='Data limite para resolução:')),
                ('dataEnvioSetorCrp', models.DateField(auto_now_add=True, verbose_name='Data de envio para setor de CRP:')),
                ('dataEnvioSetorEntrega', models.DateField(blank=True, null=True, verbose_name='Data de envio para setor de entrega:')),
                ('dataRecebimentoDocumento', models.DateField(blank=True, null=True, verbose_name='Data recebimento da CRP do setor de entrega:')),
                ('dataChegadaPeca', models.DateField(blank=True, null=True, verbose_name='Data de chegada da peça:')),
                ('dataConclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão da montagem da CRP:')),
                ('recolhimento', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Recolher peça:')),
                ('recolhida', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Peça recolhida:')),
                ('status', models.CharField(blank=True, choices=[('CANCELADO', 'CANCELADO'), ('PENDENTE', 'PENDENTE'), ('SEPARACAO', 'SEPARAÇÃO'), ('ATENDIDA', 'ATENDIDA'), ('EXPEDICAO', 'EXPEDIÇÃO'), ('REALIZADO', 'REALIZADO')], default='PENDENTE', max_length=9, verbose_name='Status dO atendimento da CRP:')),
            ],
            options={
                'verbose_name': 'CRP',
                'verbose_name_plural': "CRP's",
                'ordering': ['loja', 'numMinuta', 'numCrp', 'tipo', 'zona', 'dataPrevisaoLimite', 'recolhimento', 'recolhida', 'status'],
            },
        ),
    ]
