# Generated by Django 2.2.2 on 2019-07-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crp',
            name='recolhida',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Peça recolhida:'),
        ),
    ]
