# Generated by Django 2.2.2 on 2019-07-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0002_auto_20190707_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='solicitanteAgendamento',
            field=models.CharField(blank=True, max_length=7, verbose_name='Minuta:'),
        ),
    ]
