# Generated by Django 2.2.2 on 2019-07-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0003_minuta_solicitanteagendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuta',
            name='solicitanteAgendamento',
        ),
    ]
