# Generated by Django 2.2.2 on 2019-07-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0005_auto_20190711_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(blank=True)),
                ('dataFim', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='minuta',
            name='turnoAgendamento',
            field=models.CharField(choices=[('MANHA', 'MANHA'), ('TARDE', 'TARDE'), ('DURANTE DIA', 'DURANTE DIA')], max_length=11, verbose_name='Turno de agendamento:'),
        ),
    ]
