# Generated by Django 2.2.2 on 2019-07-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0006_auto_20190715_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='status',
            field=models.CharField(blank=True, choices=[('REALIZADO', 'REALIZADO'), ('AGENDADO', 'AGENDADO'), ('CANCELADO', 'CANCELADO')], max_length=9, verbose_name='Status de montagem:'),
        ),
    ]
